stages:
  prepare:
    cmd: python src/prepare.py
    deps:
      - src/prepare.py
      - data/iris.csv
    outs:
      - data/prepared
  train:
    cmd: python src/train.py
    deps:
      - data/prepared
      - src/train.py
    outs:
      - model.pkl
